// auto generated by go tool dist

package runtime

const defaultGoroot = `/private/var/folders/00/0v42r000h01000cxqpysvccm003chb/T/appengine/go_appengine/goroot`
const theVersion = `go1.4.2 (appengine-1.9.19)`
var buildVersion = theVersion
