ruby '1.9.3'

source 'https://rubygems.org'

gem 'thin'
gem 'sass'
gem 'coffee-script'
gem 'sinatra'
gem "sinatra-twitter-bootstrap"
gem 'sprockets'
gem 'shotgun'
gem 'foreman', '0.60.0'
gem 'activesupport'
gem 'eco'
gem 'deano'

group :development, :test do
  gem 'pry'
end
