ruby '2.0.0'

source 'https://rubygems.org'

gem 'thin'
gem 'sass'
gem 'coffee-script'
gem 'sinatra'
gem "sinatra-twitter-bootstrap"
gem 'sprockets'
gem 'foreman', '0.60.0'
gem 'activesupport'
gem 'eco'
gem 'deano'